updating trunk to gmsh-2.2.4

diff --git a/pkgs/gmsh/configure b/pkgs/gmsh/configure
--- a/pkgs/gmsh/configure
+++ b/pkgs/gmsh/configure
@@ -1274,7 +1274,8 @@ Optional Features:
   --enable-contrib        enable contrib packages (default=yes)
   --enable-netgen         compile Netgen if available (default=yes)
   --enable-ann            compile ANN if available (default=yes)
-  --enable-metis          compile METIS if available (default=no)
+  --enable-metis          compile METIS partitioner (default=yes)
+  --enable-chaco          compile Chaco partitioner (default=yes)
   --enable-tetgen         compile Tetgen if available (default=yes)
   --enable-matheval       compile MathEval if available (default=yes)
   --enable-osmesa         use OSMesa for offscreen rendering (default=no)
@@ -1897,6 +1898,11 @@ if test "${enable_metis+set}" = set; then
   enableval=$enable_metis;
 fi
 
+# Check whether --enable-chaco was given.
+if test "${enable_chaco+set}" = set; then
+  enableval=$enable_chaco;
+fi
+
 # Check whether --enable-tetgen was given.
 if test "${enable_tetgen+set}" = set; then
   enableval=$enable_tetgen;
@@ -1950,19 +1956,26 @@ fi
 
 if test "x$enable_minimal" = "xyes"; then
   enable_gui=no;
-  enable_parser=no;
-  enable_post=no;
   enable_gsl=no;
-#  enable_occ=no;
   enable_fm=no;
   enable_netgen=no;
   enable_tetgen=no;
   enable_matheval=no;
   enable_ann=no;
   enable_metis=no;
+  enable_chaco=no;
   enable_med=no;
   enable_cgns=no;
   enable_zlib=no;
+  if test "x$enable_post" != "xyes"; then
+    enable_post=no;
+  fi
+  if test "x$enable_parser" != "xyes"; then
+    enable_parser=no;
+  fi
+  if test "x$enable_occ" != "xyes"; then
+    enable_occ=no;
+  fi
   CXXFLAGS=-O2;
 fi
 
@@ -3499,7 +3512,7 @@ case "$UNAME" in
       UNAME="${UNAME}-no-cygwin"
       CC="${CC} -mno-cygwin"
       CXX="${CXX} -mno-cygwin"
-                  LINKER="${LINKER} -mno-cygwin -Wl,--stack,16777216"
+      LINKER="${LINKER} -mno-cygwin"
     fi
     ;;
 esac
@@ -4369,93 +4382,6 @@ else
   FLAGS="-DHAVE_NO_VSNPRINTF ${FLAGS}"
 fi
 
-{ echo "$as_me:$LINENO: checking for snprintf" >&5
-echo $ECHO_N "checking for snprintf... $ECHO_C" >&6; }
-if test "${ac_cv_func_snprintf+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-/* Define snprintf to an innocuous variant, in case <limits.h> declares snprintf.
-   For example, HP-UX 11i <limits.h> declares gettimeofday.  */
-#define snprintf innocuous_snprintf
-
-/* System header to define __stub macros and hopefully few prototypes,
-    which can conflict with char snprintf (); below.
-    Prefer <limits.h> to <assert.h> if __STDC__ is defined, since
-    <limits.h> exists even on freestanding compilers.  */
-
-#ifdef __STDC__
-# include <limits.h>
-#else
-# include <assert.h>
-#endif
-
-#undef snprintf
-
-/* Override any GCC internal prototype to avoid an error.
-   Use char because int might match the return type of a GCC
-   builtin and then its argument prototype would still apply.  */
-#ifdef __cplusplus
-extern "C"
-#endif
-char snprintf ();
-/* The GNU C library defines this for functions which it implements
-    to always fail with ENOSYS.  Some functions are actually named
-    something starting with __ and the normal name is an alias.  */
-#if defined __stub_snprintf || defined __stub___snprintf
-choke me
-#endif
-
-int
-main ()
-{
-return snprintf ();
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (ac_try="$ac_link"
-case "(($ac_try" in
-  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
-  *) ac_try_echo=$ac_try;;
-esac
-eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
-  (eval "$ac_link") 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } && {
-	 test -z "$ac_cxx_werror_flag" ||
-	 test ! -s conftest.err
-       } && test -s conftest$ac_exeext &&
-       $as_test_x conftest$ac_exeext; then
-  ac_cv_func_snprintf=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-	ac_cv_func_snprintf=no
-fi
-
-rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
-      conftest$ac_exeext conftest.$ac_ext
-fi
-{ echo "$as_me:$LINENO: result: $ac_cv_func_snprintf" >&5
-echo "${ECHO_T}$ac_cv_func_snprintf" >&6; }
-if test $ac_cv_func_snprintf = yes; then
-  :
-else
-  FLAGS="-DHAVE_NO_SNPRINTF ${FLAGS}"
-fi
-
 
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
@@ -4502,6 +4428,7 @@ rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
 
 if test "x$enable_contrib" != "xno"; then
 
+    if test "x$enable_ann" != "xno"; then
     { echo "$as_me:$LINENO: checking for ./contrib/ANN/include/ANN/ANN.h" >&5
 echo $ECHO_N "checking for ./contrib/ANN/include/ANN/ANN.h... $ECHO_C" >&6; }
 if test "${ac_cv_file___contrib_ANN_include_ANN_ANN_h+set}" = set; then
@@ -4525,32 +4452,59 @@ else
   ANN="no"
 fi
 
-  if test "x${ANN}" != "xno"; then
-    if test "x$enable_ann" != "xno"; then
-       GMSH_DIRS="${GMSH_DIRS} contrib/ANN"
-       GMSH_LIBS="${GMSH_LIBS} -lGmshANN"
-       FLAGS="-DHAVE_ANN ${FLAGS}"
-       echo "********************************************************************"
-       echo "You are building a version of Gmsh that contains ANN, the"
-       echo "Approximate Nearest Neighbor library."
-       echo "Please note that by doing so, you agree with ANN's licensing"
-       echo "requirements stated in ./contrib/ANN/Copyright.txt."
-       echo "To disable ANN, run configure again with the --disable-ann"
-       echo "option."
-       echo "********************************************************************"
-    fi
-  else
-    if test "x$enable_ann" != "xno"; then
-       echo "********************************************************************"
-       echo "If you want to use ANN for doing fast geometrical searchs in the"
-       echo "STL mesher, please download ANN from the author's web site at"
-       echo "http://www.cs.umd.edu/~mount/ANN/, unpack the archive and copy both"
-       echo "src and include directories in the /contrib/ANN subdirectory. Then"
-       echo "run ./configure again."
-       echo "********************************************************************"
+    if test "x${ANN}" = "xyes"; then
+      GMSH_DIRS="${GMSH_DIRS} contrib/ANN"
+      GMSH_LIBS="${GMSH_LIBS} -lGmshANN"
+      FLAGS="-DHAVE_ANN ${FLAGS}"
+      echo "********************************************************************"
+      echo "  You are building a version of Gmsh that contains ANN, the"
+      echo "  Approximate Nearest Neighbor library."
+      echo "  Please note that by doing so, you agree with ANN's licensing"
+      echo "  requirements stated in contrib/ANN/Copyright.txt."
+      echo "  To disable ANN, run configure again with the --disable-ann"
+      echo "  option."
+      echo "********************************************************************"
     fi
   fi
 
+    if test "x$enable_chaco" != "xno"; then
+    { echo "$as_me:$LINENO: checking for ./contrib/Chaco/main/interface.c" >&5
+echo $ECHO_N "checking for ./contrib/Chaco/main/interface.c... $ECHO_C" >&6; }
+if test "${ac_cv_file___contrib_Chaco_main_interface_c+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  test "$cross_compiling" = yes &&
+  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+if test -r "./contrib/Chaco/main/interface.c"; then
+  ac_cv_file___contrib_Chaco_main_interface_c=yes
+else
+  ac_cv_file___contrib_Chaco_main_interface_c=no
+fi
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_file___contrib_Chaco_main_interface_c" >&5
+echo "${ECHO_T}$ac_cv_file___contrib_Chaco_main_interface_c" >&6; }
+if test $ac_cv_file___contrib_Chaco_main_interface_c = yes; then
+  CHACO="yes"
+else
+  CHACO="no"
+fi
+
+    if test "x${CHACO}" = "xyes"; then
+      GMSH_DIRS="${GMSH_DIRS} contrib/Chaco"
+      GMSH_LIBS="${GMSH_LIBS} -lGmshChaco"
+      FLAGS="${FLAGS} -DHAVE_CHACO"
+      echo "********************************************************************"
+      echo "  You are building a version of Gmsh that contains the Chaco mesh"
+      echo "  partitioner. Chaco is available under the GNU LGPL."
+      echo "  To disable Chaco, run configure again with the --disable-chaco"
+      echo "  option."
+      echo "********************************************************************"
+    fi
+  fi
+
+    if test "x$enable_metis" != "xno"; then
     { echo "$as_me:$LINENO: checking for ./contrib/Metis/metis.h" >&5
 echo $ECHO_N "checking for ./contrib/Metis/metis.h... $ECHO_C" >&6; }
 if test "${ac_cv_file___contrib_Metis_metis_h+set}" = set; then
@@ -4574,32 +4528,22 @@ else
   METIS="no"
 fi
 
-  if test "x${METIS}" = "xyes"; then
-    if test "x$enable_metis" = "xyes"; then
-       GMSH_DIRS="${GMSH_DIRS} contrib/Metis"
-       GMSH_LIBS="${GMSH_LIBS} -lGmshMetis"
-       FLAGS="-DHAVE_METIS ${FLAGS}"
-       echo "********************************************************************"
-       echo "You are building a version of Gmsh that contains METIS, the"
-       echo "Serial Graph Partitioner."
-       echo "Please note that by doing so, you agree with METIS's licensing"
-       echo "requirements stated in ./contrib/Metis/README."
-       echo "To disable METIS, run configure again with the --disable-metis"
-       echo "option."
-       echo "********************************************************************"
-    fi
-  else
-    if test "x$enable-metis" = "xyes"; then
-       echo "********************************************************************"
-       echo "If you want to use METIS for doing mesh partitioning, please"
-       echo "download METIS from the author's web site at"
-       echo "http://www-users.cs.umn.edu/~karypis/metis/, unpack the archive and"
-       echo "copy the Lib Directory in the ./contrib/Metis subdirectory. Then"
-       echo "run ./configure again."
-       echo "********************************************************************"
+    if test "x${METIS}" = "xyes"; then
+      GMSH_DIRS="${GMSH_DIRS} contrib/Metis"
+      GMSH_LIBS="${GMSH_LIBS} -lGmshMetis"
+      FLAGS="${FLAGS} -DHAVE_METIS"
+      echo "********************************************************************"
+      echo "  You are building a version of Gmsh that contains the METIS mesh"
+      echo "  partitioner."
+      echo "  Please note that by including METIS, you agree with the METIS"
+      echo "  licensing requirements stated in contrib/Metis/README."
+      echo "  To disable METIS, run configure again with the --disable-metis"
+      echo "  option."
+      echo "********************************************************************"
     fi
   fi
 
+    if test "x$enable_netgen" != "xno"; then
     { echo "$as_me:$LINENO: checking for ./contrib/Netgen/libsrc/meshing/meshclass.cpp" >&5
 echo $ECHO_N "checking for ./contrib/Netgen/libsrc/meshing/meshclass.cpp... $ECHO_C" >&6; }
 if test "${ac_cv_file___contrib_Netgen_libsrc_meshing_meshclass_cpp+set}" = set; then
@@ -4623,33 +4567,20 @@ else
   NETGEN="no"
 fi
 
-  if test "x${NETGEN}" = "xyes"; then
-    if test "x$enable_netgen" != "xno"; then
-       GMSH_DIRS="${GMSH_DIRS} contrib/Netgen"
-       GMSH_LIBS="${GMSH_LIBS} -lGmshNetgen"
-       FLAGS="-DHAVE_NETGEN ${FLAGS}"
-       echo "********************************************************************"
-       echo "You are building a version of Gmsh that contains Joachim Schoberl's"
-       echo "Netgen as an alternative 3D mesh generator. Netgen is distributed"
-       echo "under the GNU LGPL: see ./contrib/Netgen/COPYING.LIB for more info."
-       echo "To disable Netgen, run configure again with the --disable-netgen"
-       echo "option."
-       echo "********************************************************************"
-    fi
-  else
-    if test "x$enable_netgen" != "xno"; then
-       echo "********************************************************************"
-       echo "If you want to use Joachim Schoberl's Netgen as an alternative"
-       echo "3D mesh generator, please download Netgen from the project's"
-       echo "web site at http://www.hpfem.jku.at/netgen/, unpack the archive"
-       echo "and move the libsrc subdirectory in the ./contrib/Netgen"
-       echo "subdirectory. Then run ./configure again."
-       echo "Please note that by doing so, you agree with Netgen's licensing"
-       echo "requirements stated in ./contrib/Netgen/COPYING.LIB."
-       echo "********************************************************************"
+    if test "x${NETGEN}" = "xyes"; then
+      GMSH_DIRS="${GMSH_DIRS} contrib/Netgen"
+      GMSH_LIBS="${GMSH_LIBS} -lGmshNetgen"
+      FLAGS="-DHAVE_NETGEN ${FLAGS}"
+      echo "********************************************************************"
+      echo "  You are building a version of Gmsh that contains the Netgen 3D"
+      echo "  mesh generator. Netgen is distributed under the GNU LGPL."
+      echo "  To disable Netgen, run configure again with the --disable-netgen"
+      echo "  option."
+      echo "********************************************************************"
     fi
   fi
 
+    if test "x$enable_tetgen" != "xno"; then
     { echo "$as_me:$LINENO: checking for ./contrib/Tetgen/tetgen.h" >&5
 echo $ECHO_N "checking for ./contrib/Tetgen/tetgen.h... $ECHO_C" >&6; }
 if test "${ac_cv_file___contrib_Tetgen_tetgen_h+set}" = set; then
@@ -4673,33 +4604,19 @@ else
   TETGEN="no"
 fi
 
-  if test "x${TETGEN}" = "xyes"; then
-    if test "x$enable_tetgen" != "xno"; then
-       GMSH_DIRS="${GMSH_DIRS} contrib/Tetgen"
-       GMSH_LIBS="${GMSH_LIBS} -lGmshTetgen"
-       FLAGS="-DHAVE_TETGEN ${FLAGS}"
-       echo "********************************************************************"
-       echo "You are building a version of Gmsh that contains Hang Si's"
-       echo "Tetgen as an alternative 3D mesh generator."
-       echo "Please note that by doing so, you agree with Tetgen's licensing"
-       echo "requirements stated in ./contrib/Tetgen/LICENSE. (Most notably, you"
-       echo "may then only redistribute Gmsh for non-commercial purposes.)"
-       echo "To disable Tetgen, run configure again with the --disable-tetgen"
-       echo "option."
-       echo "********************************************************************"
-    fi
-  else
-    if test "x$enable_tetgen" != "xno"; then
-       echo "********************************************************************"
-       echo "If you want to use Hang Si's Tetgen as an alternative"
-       echo "3D mesh generator, please download Tetgen from the project's"
-       echo "web site at http://www.tetgen.berlios.de, unpack the archive"
-       echo "and move the files predicates.cxx, tetgen.cxx and tetgen.h in"
-       echo "the ./contrib/Tetgen subdirectory. Then run ./configure again."
-       echo "Please note that by doing so, you agree with Tetgen's licensing"
-       echo "requirements stated in ./contrib/Tetgen/LICENSE. (Most notably, you"
-       echo "may then only redistribute Gmsh if no compensation is received.)"
-       echo "********************************************************************"
+    if test "x${TETGEN}" = "xyes"; then
+      GMSH_DIRS="${GMSH_DIRS} contrib/Tetgen"
+      GMSH_LIBS="${GMSH_LIBS} -lGmshTetgen"
+      FLAGS="-DHAVE_TETGEN ${FLAGS}"
+      echo "********************************************************************"
+      echo "  You are building a version of Gmsh that contains the Tetgen 3D"
+      echo "  mesh generator."
+      echo "  Please note that by doing so, you agree with Tetgen's licensing"
+      echo "  requirements stated in contrib/Tetgen/LICENSE. (Most notably,"
+      echo "  you may then only redistribute Gmsh for non-commercial purposes.)"
+      echo "  To disable Tetgen, run configure again with the --disable-tetgen"
+      echo "  option."
+      echo "********************************************************************"
     fi
   fi
 
@@ -4902,26 +4819,14 @@ fi
 
   if test "x${NR}" = "xyes"; then
     echo "********************************************************************"
-    echo "You are building a non-free version of Gmsh, using code copyright"
-    echo "(C) 1986-92 Numerical Recipes Software J!0."
-    echo "To use the GSL instead, run configure again with the --enable-gsl"
-    echo "option."
+    echo "  You are building a non-free version of Gmsh, using code copyright"
+    echo "  (C) 1986-92 Numerical Recipes Software J!0."
+    echo "  To use the GSL instead, run configure again with the --enable-gsl"
+    echo "  option."
     echo "********************************************************************"
     GMSH_DIRS="${GMSH_DIRS} contrib/NR"
     GMSH_LIBS="${GMSH_LIBS} -lGmshNR"
   else
-    echo "********************************************************************"
-    echo "This is the free version of Gmsh and configure could not find"
-    echo "the GNU Scientific Library (GSL) on your system:"
-    echo "- if it is installed in a non-standard location, please run"
-    echo "  configure again with the --with-gsl-prefix option"
-    echo "- if it is not installed on your system, you can download it from"
-    echo "  http://sources.redhat.com/gsl/"
-    echo ""
-    echo "IMPORTANT NOTE: You need to install GSL version 1.2 or above. All"
-    echo "versions <= 1.1.1 have a bug in the singular value decomposition"
-    echo "algorithm that will cause Gmsh to hang during mesh generation."
-    echo "********************************************************************"
     { { echo "$as_me:$LINENO: error: Could not find GSL, aborting." >&5
 echo "$as_me: error: Could not find GSL, aborting." >&2;}
    { (exit 1); exit 1; }; }
@@ -5850,7 +5755,7 @@ GMSH_LIBS="${GMSH_LIBS} -lm"
 case "$UNAME" in
 
   CYGWIN* | MINGW*)
-    LINKER="${LINKER} -mwindows"
+            LINKER="${LINKER} -mwindows -Wl,--stack,16777216"
     if test "x$enable_cygwin" != "xyes"; then
       FLAGS="${FLAGS} -DHAVE_NO_DLL"
     fi
@@ -7991,12 +7896,12 @@ fi
 
 echo "********************************************************************"
 echo "Gmsh is configured for"
-echo "- OS           : $UNAME on $HOSTNAME"
-echo "- C compiler   : $CC"
-echo "- C++ compiler : $CXX"
-echo "- Linker       : $LINKER"
-echo "- Optimization : $OPTIM"
-echo "- Options      : $FLAGS"
+echo "  - OS           : $UNAME on $HOSTNAME"
+echo "  - C compiler   : $CC"
+echo "  - C++ compiler : $CXX"
+echo "  - Linker       : $LINKER"
+echo "  - Optimization : $OPTIM"
+echo "  - Options      : $FLAGS"
 echo "********************************************************************"
 echo "To fine-tune the configuration, edit the 'variables' file"
 echo "********************************************************************"
