move gmsh to 2.2.6

diff --git a/pkgs/gmsh/configure b/pkgs/gmsh/configure
--- a/pkgs/gmsh/configure
+++ b/pkgs/gmsh/configure
@@ -1278,6 +1278,7 @@ Optional Features:
   --enable-chaco          compile Chaco partitioner (default=yes)
   --enable-tetgen         compile Tetgen if available (default=yes)
   --enable-matheval       compile MathEval if available (default=yes)
+  --enable-gmm            use gmm++ if available (default=yes)
   --enable-osmesa         use OSMesa for offscreen rendering (default=no)
   --enable-cgns           enable CGNS output (default=no)
   --enable-occ            enable OpenCascade support (default=no)
@@ -1913,6 +1914,11 @@ if test "${enable_matheval+set}" = set; then
   enableval=$enable_matheval;
 fi
 
+# Check whether --enable-gmm was given.
+if test "${enable_gmm+set}" = set; then
+  enableval=$enable_gmm;
+fi
+
 # Check whether --enable-osmesa was given.
 if test "${enable_osmesa+set}" = set; then
   enableval=$enable_osmesa;
@@ -1961,6 +1967,7 @@ if test "x$enable_minimal" = "xyes"; then
   enable_netgen=no;
   enable_tetgen=no;
   enable_matheval=no;
+  enable_gmm=no;
   enable_ann=no;
   enable_metis=no;
   enable_chaco=no;
@@ -3680,7 +3687,7 @@ esac
 if test "x$enable_gui" != "xno"; then
 
   GMSH_DIRS="Common Geo Mesh Post Plugin Numeric Parser Graphics Fltk"
-  GMSH_LIBS="-Llib -lGmshFltk -lGmshCommon -lGmshGeo -lGmshMesh -lGmshPost -lGmshPlugin"
+  GMSH_LIBS="-Llib -lGmshFltk -lGmshCommon -lGmshMesh -lGmshGeo -lGmshPost -lGmshPlugin"
   GMSH_LIBS="${GMSH_LIBS} -lGmshCommon -lGmshGraphics -lGmshParser -lGmshNumeric"
   FLAGS="-DHAVE_FLTK ${FLAGS}"
 
@@ -4140,7 +4147,7 @@ fi
 else
 
   GMSH_DIRS="Common Geo Mesh"
-  GMSH_LIBS="-Llib Common/Main.o -lGmshCommon -lGmshGeo -lGmshMesh"
+  GMSH_LIBS="-Llib Common/Main.o -lGmshCommon -lGmshMesh -lGmshGeo"
 
   if test "x$enable_post" != "xno"; then
     GMSH_DIRS="${GMSH_DIRS} Post Plugin"
@@ -4458,10 +4465,44 @@ fi
       FLAGS="-DHAVE_ANN ${FLAGS}"
       echo "********************************************************************"
       echo "  You are building a version of Gmsh that contains ANN, the"
-      echo "  Approximate Nearest Neighbor library."
-      echo "  Please note that by doing so, you agree with ANN's licensing"
-      echo "  requirements stated in contrib/ANN/Copyright.txt."
+      echo "  Approximate Nearest Neighbor library. ANN is available under"
+      echo "  the GNU LGPL."
       echo "  To disable ANN, run configure again with the --disable-ann"
+      echo "  option."
+      echo "********************************************************************"
+    fi
+  fi
+
+    if test "x$enable_gmm" != "xno"; then
+    { echo "$as_me:$LINENO: checking for ./contrib/gmm/gmm.h" >&5
+echo $ECHO_N "checking for ./contrib/gmm/gmm.h... $ECHO_C" >&6; }
+if test "${ac_cv_file___contrib_gmm_gmm_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  test "$cross_compiling" = yes &&
+  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+if test -r "./contrib/gmm/gmm.h"; then
+  ac_cv_file___contrib_gmm_gmm_h=yes
+else
+  ac_cv_file___contrib_gmm_gmm_h=no
+fi
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_file___contrib_gmm_gmm_h" >&5
+echo "${ECHO_T}$ac_cv_file___contrib_gmm_gmm_h" >&6; }
+if test $ac_cv_file___contrib_gmm_gmm_h = yes; then
+  GMM="yes"
+else
+  GMM="no"
+fi
+
+    if test "x${GMM}" = "xyes"; then
+      FLAGS="${FLAGS} -DHAVE_GMM"
+      echo "********************************************************************"
+      echo "  You are building a version of Gmsh that contains the gmm++ mesh"
+      echo "  partitioner. Gmm++ is available under the GNU LGPL."
+      echo "  To disable gmm++, run configure again with the --disable-gmm"
       echo "  option."
       echo "********************************************************************"
     fi
@@ -4535,8 +4576,8 @@ fi
       echo "********************************************************************"
       echo "  You are building a version of Gmsh that contains the METIS mesh"
       echo "  partitioner."
-      echo "  Please note that by including METIS, you agree with the METIS"
-      echo "  licensing requirements stated in contrib/Metis/README."
+      echo "  Please note that by including METIS, you agree with METIS'"
+      echo "  special licensing requirements stated in contrib/Metis/README."
       echo "  To disable METIS, run configure again with the --disable-metis"
       echo "  option."
       echo "********************************************************************"
@@ -4573,7 +4614,7 @@ fi
       FLAGS="-DHAVE_NETGEN ${FLAGS}"
       echo "********************************************************************"
       echo "  You are building a version of Gmsh that contains the Netgen 3D"
-      echo "  mesh generator. Netgen is distributed under the GNU LGPL."
+      echo "  mesh generator. Netgen is available under the GNU LGPL."
       echo "  To disable Netgen, run configure again with the --disable-netgen"
       echo "  option."
       echo "********************************************************************"
@@ -4611,9 +4652,8 @@ fi
       echo "********************************************************************"
       echo "  You are building a version of Gmsh that contains the Tetgen 3D"
       echo "  mesh generator."
-      echo "  Please note that by doing so, you agree with Tetgen's licensing"
-      echo "  requirements stated in contrib/Tetgen/LICENSE. (Most notably,"
-      echo "  you may then only redistribute Gmsh for non-commercial purposes.)"
+      echo "  Please note that by doing so, you agree with Tetgen's special"
+      echo "  licensing requirements stated in contrib/Tetgen/LICENSE."
       echo "  To disable Tetgen, run configure again with the --disable-tetgen"
       echo "  option."
       echo "********************************************************************"
@@ -4648,6 +4688,12 @@ fi
       GMSH_DIRS="${GMSH_DIRS} contrib/MathEval"
       GMSH_LIBS="${GMSH_LIBS} -lGmshMathEval"
       FLAGS="-DHAVE_MATH_EVAL ${FLAGS}"
+      echo "********************************************************************"
+      echo "  You are building a version of Gmsh that contains GNU MathEval."
+      echo "  MathEval is available under the GNU GPL."
+      echo "  To disable MathEval, run configure again with the"
+      echo "  --disable-matheval option."
+      echo "********************************************************************"
     fi
   fi
 
@@ -4818,20 +4864,21 @@ else
 fi
 
   if test "x${NR}" = "xyes"; then
+    GMSH_DIRS="${GMSH_DIRS} contrib/NR"
+    GMSH_LIBS="${GMSH_LIBS} -lGmshNR"
     echo "********************************************************************"
     echo "  You are building a non-free version of Gmsh, using code copyright"
-    echo "  (C) 1986-92 Numerical Recipes Software J!0."
+    echo "  (C) 1986-92 Numerical Recipes Software."
     echo "  To use the GSL instead, run configure again with the --enable-gsl"
     echo "  option."
     echo "********************************************************************"
-    GMSH_DIRS="${GMSH_DIRS} contrib/NR"
-    GMSH_LIBS="${GMSH_LIBS} -lGmshNR"
   else
     { { echo "$as_me:$LINENO: error: Could not find GSL, aborting." >&5
 echo "$as_me: error: Could not find GSL, aborting." >&2;}
    { (exit 1); exit 1; }; }
   fi
 fi
+
 
 if test "x${CGNS_PREFIX}" != "x"; then
   if test "x$enable_cgns" != "xno"; then
